version: '2'

services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./Docker/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/my_app

  mysql:
    image: mysql:5.7
    volumes:
      - ./Docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root

  php:
    build:
      dockerfile: Dockerfile
      context: ./Docker/php7-fpm
      args:
        UID: 501
    volumes:
      - .:/var/www/my_app

  redis:
    build:
      dockerfile: Dockerfile
      context: ./Docker/redis
    ports:
      - 6379:6379

  eventstore:
    image: adbrowne/eventstore
    ports:
      - 2113:2113
    expose:
      - 2113
    volumes:
      - ./data/db:/data/db
      - ./data/logs:/data/logs

  memcached:
    image: memcached:1.4
    ports:
      - 11211:11211